### ISSUE TITLE
Could not your addon summarize at higher levels?

### ISSUE THREAD

**Issue by cjdduarte** [glfharris/Syllabus#1]
Congratulations on your addon.
I have some questions.

I use many subdecks in this version 2.1 because of the experimental scheduler. See I use an addon that puts more columns. Could not your addon summarize at higher levels?
See the comparison:

![image](https://user-images.githubusercontent.com/42243532/45849593-e8ec7a00-bd08-11e8-91dd-9af136b488ef.png)

![image](https://user-images.githubusercontent.com/42243532/45849716-8e075280-bd09-11e8-8a1a-4635cfc0530a.png)

**Comment by glfharris** [comment]
Hi!

Ah ha, I see what you mean! Hmm yes that's definitely an issue, I'll get working on it!

Must have missed it as my anki pattern is to not use many sub decks.

Cheers,
George

**Comment by glfharris** [comment]
That's fixed as of v0.1.1, if you update the addon inside anki you should have that problem anymore.

**Comment by cjdduarte** [comment]
It worked. Congratulations again.

Now suggestion of future improvement or a new addon:

The possibility of triggering the statistics by tags. Your addon was one of the few I saw that can quantify statistics by tag. So I think it's not hard to trigger Anki's statistics by tag.

![image](https://user-images.githubusercontent.com/42243532/45851406-1b9a7080-bd11-11e8-9cd5-d4aa94400f5f.png)

![image](https://user-images.githubusercontent.com/42243532/45851415-294ff600-bd11-11e8-8c0b-c3f4b5cd3e99.png)

**Comment by glfharris** [comment]
I'll look into it, thanks for the suggestion!
