### ISSUE TITLE
improvement suggestion - Average of the "ease" column

### ISSUE THREAD

**Issue by cjdduarte** [glfharris/Syllabus#2]
Would it be difficult to include the information of the average difficulty (average of the "ease" column)?

![image](https://user-images.githubusercontent.com/42243532/46066934-0035c800-c14c-11e8-8bfd-9aee1c287357.png)

It would be interesting to know which tags are doing better or worse

**Comment by glfharris** [comment]
Thanks for the suggestion, I'm working on it, just haven't found a specific method I like just yet.

Basically, all the current columns don't touch the revlog table (the one that has an entry for each review), and I'm working on a set of methods to touch the revlog, just haven't made a clean enough set yet.

**Comment by cjdduarte** [comment]
Thanks for the feedback. I wait then.

**Comment by glfharris** [comment]
Added as of v0.1.3

**Comment by cjdduarte** [comment]
I looked at the column here. I will evaluate more in detail.
Depending on, I'll open a new topic specific to it.

Thank you again.
