### ISSUE TITLE
The "Ease" column average is low.

### ISSUE THREAD

**Issue by cjdduarte** [glfharris/Syllabus#4]
I looked here, and saw that you are considered in the calculation, all the cards in the database.
The problem is that new or learning cards have a value of 0 (zero), because they have not yet been delivered to the Anki scheduler, playing the average to a very low value.

![image](https://user-images.githubusercontent.com/42243532/46114504-4e3ce100-c1c9-11e8-9dd1-fcedb83b38d1.png)

![image](https://user-images.githubusercontent.com/42243532/46114567-8b08d800-c1c9-11e8-84c3-ae4b81f3f5d2.png)

Only the cards under review should be computed (queue == 2). I have not yet considered the hanging cards (-3, -2 or -1).

**I made this change:**
```
def ease(deck=None, tag=None):
    cond = '(cards.queue == 2)'
    inner_q = _as(_c_n_query('cards.factor as factor', deck=deck, tag=tag, card_cond=[cond]), 'cards_notes')
    tmp = 'select avg(factor) from {}'.format(inner_q)
    return mw.col.db.scalar(tmp)
```

![image](https://user-images.githubusercontent.com/42243532/46114718-429dea00-c1ca-11e8-9a41-ddecb2be7c73.png)

I await your considerations.

**Comment by glfharris** [comment]
Are you using the latest version, which has:
```
def ease(deck=None, tag=None):
    inner_q = _as(_c_n_query('cards.factor as factor', deck=deck, tag=tag, card_cond=['cards.factor > 0']), 'cards_notes')
    tmp = 'select avg(factor) from {}'.format(inner_q)
    return mw.col.db.scalar(tmp)
```
The `factor > 0` condition should remove this. Now whether or not to include suspended or buried cards is a different question. At the moment I'm leaning yes, as anki can suspend cards if they're too difficult, which might be something people want to see in the stats. Thoughts?

**Comment by cjdduarte** [comment]
I agree with your solution.

I thought of the cards that are actually being studied, but this condition "cards.factor> 0" solved.
Subsequently, a second new column could be used.

I'll finalize the topic.
