### ISSUE TITLE
 Some Small Bugs:

### ISSUE THREAD

**Issue by cjdduarte** [glfharris/Syllabus#5]
**1 -** The initial column settings shows the "Young" column that does not exist in the left menu.
![image](https://user-images.githubusercontent.com/42243532/46245031-2ebad980-c3be-11e8-862b-3beab209a31a.png)

**2 -** When you enable to show the other columns and clicking "apply columns", the horizontal scroll bar does not appear to see the new columns. I am forced to resize the window for whom the scroll bar appears.
![image](https://user-images.githubusercontent.com/42243532/46245080-c91b1d00-c3be-11e8-8f30-f893d60b8e75.png)

After resizing
![image](https://user-images.githubusercontent.com/42243532/46245103-13040300-c3bf-11e8-8e12-0e6e39ff0e5c.png)

**3 -** When I close the "Syllabus" window and open again, it loses the settings I made. It is not necessarily a bug, but it can be a suggestion for improvement. The improvement does not need to "Save" settings in the user profile, but at least stay in memory until I close Anki.

**4 -** The default window size might be a bit larger in the vertical, so you do not need to resize it
![image](https://user-images.githubusercontent.com/42243532/46245155-c2d97080-c3bf-11e8-9b0b-a1d312231e66.png)

5 - What is the purpose of this "Deck" column. In my show big numbers.
![image](https://user-images.githubusercontent.com/42243532/46245232-e6e98180-c3c0-11e8-9433-ac758bab7c0e.png)

**6 -** Would it be possible to automatically translate the languages? Anki uses an idiom library and automatically translates some terms.

![image](https://user-images.githubusercontent.com/42243532/46245205-6b87d000-c3c0-11e8-83ee-7a6da75228f9.png)

**Comment by glfharris** [comment]
1. Done
2. Yeah that's strange, now made it resize after each tree generation
3. Added storing last columns in config
4. Done
5. Deck is there as a bit of admin, its the deck id for that tag/deck. Basically having it there allows full resolution of that node without having to look at children or parents. In the future its there to let me do things like right click > open in browser/stats etc. 
6. I'll have a look at this, it looks like it should be possible, but I don't have any experience doing it so I'll stick it in a features to do.

**Comment by cjdduarte** [comment]
Thank you, now it's OK.

> 6. I'll have a look at this, it looks like it should be possible, but I don't have any experience doing it so I'll stick it in a features to do.

OK
